CREATE TABLE IF NOT EXISTS tenants (id TEXT PRIMARY KEY, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS api_tokens (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, token_hash TEXT NOT NULL UNIQUE, role TEXT NOT NULL DEFAULT 'tenant', status TEXT NOT NULL DEFAULT 'active', created_at TEXT NOT NULL, last_used_at TEXT);
ALTER TABLE tasks ADD COLUMN tenant_id TEXT NOT NULL DEFAULT '__legacy__';
ALTER TABLE tasks ADD COLUMN workflow_id TEXT;
ALTER TABLE tasks ADD COLUMN max_steps INTEGER NOT NULL DEFAULT 30;
ALTER TABLE tasks ADD COLUMN max_retries INTEGER NOT NULL DEFAULT 3;
CREATE TABLE IF NOT EXISTS task_results (id TEXT PRIMARY KEY, task_id TEXT NOT NULL, tenant_id TEXT NOT NULL, step TEXT NOT NULL, result TEXT NOT NULL, created_at TEXT NOT NULL);
ALTER TABLE approvals ADD COLUMN tenant_id TEXT NOT NULL DEFAULT '__legacy__';
ALTER TABLE approvals ADD COLUMN step TEXT NOT NULL DEFAULT 'unknown';
ALTER TABLE approvals ADD COLUMN expires_at TEXT NOT NULL DEFAULT '2099-01-01T00:00:00.000Z';
CREATE TABLE IF NOT EXISTS audit_log (id TEXT PRIMARY KEY, ts TEXT NOT NULL, actor_id TEXT, actor_role TEXT, tenant_id TEXT, type TEXT NOT NULL, payload TEXT NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS system_controls (id INTEGER PRIMARY KEY CHECK(id=1), enabled INTEGER NOT NULL DEFAULT 1, updated_at TEXT NOT NULL);
INSERT OR IGNORE INTO system_controls(id,enabled,updated_at) VALUES(1,1,datetime('now'));
CREATE INDEX IF NOT EXISTS idx_tasks_tenant_status ON tasks(tenant_id,status,priority,created_at);
CREATE INDEX IF NOT EXISTS idx_results_tenant ON task_results(tenant_id,created_at);
CREATE INDEX IF NOT EXISTS idx_approvals_tenant ON approvals(tenant_id,status,created_at);
CREATE INDEX IF NOT EXISTS idx_audit_tenant ON audit_log(tenant_id,ts DESC);
